changes made into new branch previous branch was outdated
US-EPA-CAMD/easey-auth-api pull request #177
Opened 2024-02-12 16:12 UTC by shahbazkhan1999

2024-03-11 20:00 UTC, maxdiebold-erg requested changes
I left one minor suggestion below.

I think this should work for the API side, but I'm not sure about the UI side. Does the "Initial Authorizer" role need to be added to the conditional of the `retrieveAllUserFacilities` function in `Permissions.service.ts`?

2024-03-11 20:00 UTC, maxdiebold-erg commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
For consistency, this should match the error in the response:
```suggestion
        new Error('This requires the Sponsor or Submitter or Initial Authorizer role'),
```

2024-03-11 20:17 UTC, shahbazkhan1999 commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
these changes are already been discussed

2024-03-11 20:29 UTC, maxdiebold-erg commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
Right, but looking at the linked issue, @mark-hayward-erg noted that there will be cases when the _only_ role returned is "Initial Authorizer". This issue is just for the API, so I think the ECMPS discussion can go elsewhere, but I do think the Error descriptions should probably match.

2024-03-12 15:01 UTC, shahbazkhan1999 commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
Yes but this message is already been there and approved so this will remain the same

2024-03-12 15:08 UTC, maxdiebold-erg commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
If it's already approved I'm not sure why you requested me for a review? I'll go ahead and pass this back to @spetros-do.

2024-03-12 15:11 UTC, shahbazkhan1999 commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
I got the point lemme do that.

2024-03-12 15:12 UTC, mark-hayward-erg commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
@shahbazkhan1999 @maxdiebold-erg The error message returned to the user needs to match the validation logic that is being applied.

The change here is to allow users that only have the Initial Authorizer to be able to submit, so the error message should read "This requires the Sponsor or Submitter or Initial Authorizer role".

2024-03-12 19:56 UTC, shahbazkhan1999 commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
Alright @mark-hayward-erg

2024-03-12 20:29 UTC, maxdiebold-erg commented on src/sign/Sign.service.ts
>          new Error('This requires the Sponsor or Submitter role'),
I'm thinking this is the idea:
```suggestion
        new Error('This requires the Sponsor, Submitter, or Initial Authorizer role'),
```

2024-03-12 20:29 UTC, maxdiebold-erg commented on src/sign/Sign.service.ts
> +          responseObject: 'This requires the Sponsor or Submitter or Initial Authorizer role',
Then this would be:
```suggestion
          responseObject: 'This requires the Sponsor, Submitter, or Initial Authorizer role',
```

2024-03-14 15:06 UTC, maxdiebold-erg approved these changes
Looks great, thanks for making those changes.

2024-03-14 15:07 UTC, merged